import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import Link from 'next/link';
import { ArrowLeft, AlertTriangle } from 'lucide-react';

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-background">
      <div className="container max-w-4xl mx-auto px-4 py-8">
        <div className="flex items-center gap-4 mb-6">
          <Link href="/">
            <Button variant="ghost" size="icon">
              <ArrowLeft className="h-5 w-5" />
            </Button>
          </Link>
          <h1 className="text-3xl font-bold">Terms of Service</h1>
        </div>

        <Card className="p-6 mb-6 border-yellow-500 bg-yellow-50 dark:bg-yellow-950">
          <div className="flex gap-3">
            <AlertTriangle className="h-5 w-5 text-yellow-600 mt-0.5 flex-shrink-0" />
            <div>
              <h3 className="font-semibold text-yellow-900 dark:text-yellow-100 mb-1">
                Hackathon Demo Project
              </h3>
              <p className="text-sm text-yellow-800 dark:text-yellow-200">
                This is a demonstration project created for a hackathon. This application is provided
                &quot;as is&quot; for educational and demonstration purposes only. Use at your own risk.
              </p>
            </div>
          </div>
        </Card>

        <Card className="p-8 space-y-6">
          <section>
            <h2 className="text-xl font-semibold mb-3">1. Acceptance of Terms</h2>
            <p className="text-muted-foreground">
              By accessing and using DeVPN (&quot;the Service&quot;), you accept and agree to be bound by the
              terms and provision of this agreement. This is a hackathon demonstration project and
              should not be used for production purposes.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">2. Demo & Testing Purpose</h2>
            <p className="text-muted-foreground mb-2">
              DeVPN is a proof-of-concept application demonstrating decentralized VPN technology on
              the TON blockchain. This service is:
            </p>
            <ul className="list-disc list-inside text-muted-foreground space-y-1 ml-4">
              <li>Not intended for commercial use</li>
              <li>May contain bugs, errors, or incomplete features</li>
              <li>Provided without any guarantees or warranties</li>
              <li>Subject to change or discontinuation without notice</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">3. Use of Testnet Tokens</h2>
            <p className="text-muted-foreground">
              All transactions within this application use TON testnet tokens, which have no real
              monetary value. Do not send real TON tokens to addresses generated by this application.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">4. No Privacy Guarantees</h2>
            <p className="text-muted-foreground">
              While this project demonstrates VPN concepts, it does not provide the security,
              privacy, or anonymity guarantees of production VPN services. Do not use this service
              for any activities requiring real privacy protection.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">5. User Responsibilities</h2>
            <p className="text-muted-foreground mb-2">You agree to:</p>
            <ul className="list-disc list-inside text-muted-foreground space-y-1 ml-4">
              <li>Use the Service only for testing and demonstration purposes</li>
              <li>Not attempt to exploit, hack, or misuse the Service</li>
              <li>Not use the Service for any illegal activities</li>
              <li>Understand that this is a hackathon demo with limited functionality</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">6. Limitation of Liability</h2>
            <p className="text-muted-foreground">
              The developers and contributors of DeVPN shall not be liable for any direct, indirect,
              incidental, special, consequential or exemplary damages resulting from your use or
              inability to use the Service. This includes but is not limited to loss of data,
              loss of tokens, or any other losses.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">7. No Warranty</h2>
            <p className="text-muted-foreground">
              THE SERVICE IS PROVIDED &quot;AS IS&quot; WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
              INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
              PURPOSE, OR NON-INFRINGEMENT.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">8. Modifications</h2>
            <p className="text-muted-foreground">
              We reserve the right to modify or discontinue the Service at any time without notice.
              These terms may be updated as the project evolves.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">9. Open Source</h2>
            <p className="text-muted-foreground">
              This project may be made available under an open source license. Check the project
              repository for licensing information.
            </p>
          </section>

          <section className="pt-4 border-t">
            <p className="text-sm text-muted-foreground">
              <strong>Last Updated:</strong> {new Date().toLocaleDateString()}
            </p>
            <p className="text-sm text-muted-foreground mt-2">
              For questions or concerns, please contact the development team through the project
              repository or hackathon channels.
            </p>
          </section>
        </Card>

        <div className="mt-6 text-center">
          <Link href="/">
            <Button variant="outline">Back to Home</Button>
          </Link>
        </div>
      </div>
    </div>
  );
}
