// Mock Data for Development

import { VPNNode, VPNSession, Transaction, PaymentChannel, UserProfile, ProviderNode } from '@/types';

// Mock VPN Nodes
export const mockNodes: VPNNode[] = [
  {
    id: '1',
    name: 'US-NYC-01',
    location: {
      country: 'United States',
      countryCode: 'US',
      city: 'New York',
      latitude: 40.7128,
      longitude: -74.0060,
    },
    status: 'online',
    speedTier: 'fast',
    pricing: {
      pricePerHour: 0.05,
      pricePerGB: 0.01,
      currency: 'TON',
      estimatedDailyCost: 1.2,
      estimatedMonthlyCost: 36,
      depositRequired: 0.5,
    },
    provider: {
      walletAddress: 'EQD...abc123',
      providerName: 'FastVPN Inc',
      reputationScore: 98,
      stakeAmount: 100,
      nodesOperated: 15,
      joinDate: '2024-01-15',
      verified: true,
    },
    specifications: {
      publicIP: '192.168.1.***',
      serverType: 'Dedicated',
      wireguardVersion: '1.0.20210914',
      maxCapacity: 100,
      currentLoad: 45,
      bandwidthLimit: 1000,
      cpuCores: 8,
      ram: 32,
      storage: 500,
    },
    statistics: {
      uptime: 99.8,
      averageSpeed: 850,
      totalUsersServed: 1234,
      activeSessions: 12,
      responseTime: 15,
      bandwidthData: [],
    },
    rating: 4.8,
    reviewCount: 156,
    reviews: [],
    activeUsers: 12,
    isFavorite: false,
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2024-11-20T00:00:00Z',
  },
  {
    id: '2',
    name: 'UK-LON-03',
    location: {
      country: 'United Kingdom',
      countryCode: 'GB',
      city: 'London',
      latitude: 51.5074,
      longitude: -0.1278,
    },
    status: 'online',
    speedTier: 'fast',
    pricing: {
      pricePerHour: 0.04,
      pricePerGB: 0.008,
      currency: 'TON',
      estimatedDailyCost: 0.96,
      estimatedMonthlyCost: 28.8,
      depositRequired: 0.4,
    },
    provider: {
      walletAddress: 'EQD...def456',
      providerName: 'EuroNode',
      reputationScore: 95,
      stakeAmount: 75,
      nodesOperated: 8,
      joinDate: '2024-02-10',
      verified: true,
    },
    specifications: {
      publicIP: '185.120.45.***',
      serverType: 'VPS',
      wireguardVersion: '1.0.20210914',
      maxCapacity: 50,
      currentLoad: 30,
      bandwidthLimit: 500,
      cpuCores: 4,
      ram: 16,
      storage: 250,
    },
    statistics: {
      uptime: 99.5,
      averageSpeed: 450,
      totalUsersServed: 856,
      activeSessions: 8,
      responseTime: 25,
      bandwidthData: [],
    },
    rating: 4.6,
    reviewCount: 98,
    reviews: [],
    activeUsers: 8,
    isFavorite: true,
    createdAt: '2024-02-10T00:00:00Z',
    updatedAt: '2024-11-20T00:00:00Z',
  },
  {
    id: '3',
    name: 'SG-SIN-02',
    location: {
      country: 'Singapore',
      countryCode: 'SG',
      city: 'Singapore',
      latitude: 1.3521,
      longitude: 103.8198,
    },
    status: 'online',
    speedTier: 'medium',
    pricing: {
      pricePerHour: 0.03,
      pricePerGB: 0.005,
      currency: 'TON',
      estimatedDailyCost: 0.72,
      estimatedMonthlyCost: 21.6,
      depositRequired: 0.3,
    },
    provider: {
      walletAddress: 'EQD...ghi789',
      providerName: 'Asia VPN',
      reputationScore: 92,
      stakeAmount: 50,
      nodesOperated: 5,
      joinDate: '2024-03-05',
      verified: true,
    },
    specifications: {
      publicIP: '103.45.78.***',
      serverType: 'Cloud',
      wireguardVersion: '1.0.20210914',
      maxCapacity: 30,
      currentLoad: 60,
      bandwidthLimit: 300,
      cpuCores: 4,
      ram: 8,
      storage: 100,
    },
    statistics: {
      uptime: 98.9,
      averageSpeed: 280,
      totalUsersServed: 543,
      activeSessions: 15,
      responseTime: 35,
      bandwidthData: [],
    },
    rating: 4.4,
    reviewCount: 67,
    reviews: [],
    activeUsers: 15,
    isFavorite: false,
    createdAt: '2024-03-05T00:00:00Z',
    updatedAt: '2024-11-20T00:00:00Z',
  },
];

// Mock Sessions
export const mockSessions: VPNSession[] = [
  {
    id: 'session-1',
    userId: 'user-1',
    nodeId: '1',
    nodeName: 'US-NYC-01',
    nodeLocation: {
      country: 'United States',
      countryCode: 'US',
      city: 'New York',
    },
    status: 'active',
    startTime: new Date(Date.now() - 3600000).toISOString(),
    duration: 3600,
    metrics: {
      current: {
        uploadSpeed: 25,
        downloadSpeed: 150,
        uploadData: 45,
        downloadData: 230,
        totalData: 275,
        latency: 45,
        timestamp: new Date().toISOString(),
      },
      history: [],
    },
    connection: {
      serverIP: '192.168.1.100',
      clientIP: '10.0.0.5',
      protocol: 'WireGuard',
      encryption: 'ChaCha20',
      port: 51820,
    },
    paymentChannelId: 'channel-1',
    costPerHour: 0.05,
    totalCost: 0.05,
    balanceRemaining: 4.95,
    estimatedTimeLeft: 31500,
    autoRenewal: false,
    events: [],
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// Mock Transactions
export const mockTransactions: Transaction[] = [
  {
    id: 'tx-1',
    hash: '0xabcdef123456789...',
    type: 'deposit',
    status: 'confirmed',
    description: 'Wallet top-up',
    amount: 10,
    fee: 0.005,
    to: 'EQD...abc123',
    timestamp: new Date(Date.now() - 86400000).toISOString(),
    confirmations: 15,
  },
  {
    id: 'tx-2',
    hash: '0x123456789abcdef...',
    type: 'channel_open',
    status: 'confirmed',
    description: 'Payment channel opened for US-NYC-01',
    amount: -5,
    fee: 0.002,
    from: 'EQD...abc123',
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    confirmations: 8,
    metadata: {
      channelId: 'channel-1',
      nodeId: '1',
    },
  },
];

// Mock Payment Channels
export const mockChannels: PaymentChannel[] = [
  {
    id: 'channel-1',
    contractAddress: 'EQC...channel1',
    status: 'active',
    nodeId: '1',
    nodeName: 'US-NYC-01',
    nodeLocation: {
      country: 'United States',
      city: 'New York',
    },
    lockedAmount: 5,
    usedAmount: 0.05,
    remainingAmount: 4.95,
    estimatedTimeRemaining: 31500,
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    lastActivityAt: new Date().toISOString(),
    sessionId: 'session-1',
  },
];

// Mock User Profile
export const mockUserProfile: UserProfile = {
  id: 'user-1',
  telegramId: 123456789,
  username: 'crypto_user',
  firstName: 'John',
  lastName: 'Doe',
  accountType: 'consumer',
  walletAddress: 'EQD...user123',
  memberSince: '2024-01-01T00:00:00Z',
  statistics: {
    consumer: {
      totalSessions: 156,
      totalDuration: 1232880, // ~342 hours in seconds
      totalDataUsed: 245,
      totalSpent: 12.5,
      favoriteNode: {
        id: '1',
        name: 'US-NYC-01',
      },
      mostUsedCountry: 'United States',
    },
  },
  preferences: {
    connection: {
      autoConnect: false,
      autoReconnect: true,
      preferredMethod: 'qr',
      killSwitch: true,
      splitTunneling: false,
    },
    payment: {
      defaultDuration: 6,
      autoRenewal: false,
      channelSettings: {
        autoCloseInactive: true,
        inactivityThreshold: 24,
        autoCloseWhenLow: true,
        lowBalanceThreshold: 0.5,
        closeOnSessionEnd: false,
      },
    },
    notifications: {
      session_status: true,
      payment: true,
      low_balance: true,
      node_status: true,
      earnings: false,
      announcements: true,
    },
    display: {
      theme: 'auto',
      language: 'en',
      dataUnits: 'MB-GB',
      speedUnits: 'Mbps',
      currencyDisplay: 'both',
    },
    privacy: {
      showActivityStatus: true,
      allowAnalytics: true,
      shareUsageStats: false,
    },
    advanced: {
      network: 'testnet',
      debugMode: false,
    },
  },
  achievements: [
    {
      id: 'ach-1',
      name: 'First Connection',
      description: 'Connected to your first VPN node',
      icon: '🎉',
      unlockedAt: '2024-01-05T00:00:00Z',
    },
    {
      id: 'ach-2',
      name: 'Power User',
      description: 'Completed 100 sessions',
      icon: '⚡',
      unlockedAt: '2024-08-15T00:00:00Z',
    },
  ],
  createdAt: '2024-01-01T00:00:00Z',
  updatedAt: new Date().toISOString(),
};
